version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: room_management_be_dev
    ports:
      - "3005:3005"
    env_file:
      - .env
    volumes:
      - .:/app # bind source code
      - /app/node_modules # ป้องกันทับ node_modules ใน container
    depends_on:
      - db
    command: pnpm run start:dev

  db:
    image: postgres:15
    container_name: room_management_db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: room_management
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
