services:
  app:
    build: .
    container_name: room_management_be
    ports:
      - "3005:3005"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "pnpm prisma generate &&
             pnpm prisma migrate deploy &&
             pnpm run start:dev"

  db:
    image: postgres:15
    container_name: room_management_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: room
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
